### ISSUE TITLE
missing font5x8.bin

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_MAX7219#36]
one of the functions in this library uses the file `font5x8.bin` but it's not currently present in the repo.

**Comment by caternuson** [comment]
Can you link to where `font5x8.bin` is being referenced in this library?

**Comment by FoamyGuy** [comment]
@caternuson I think it may actually be getting used through frambuf from here: https://github.com/adafruit/Adafruit_CircuitPython_MAX7219/blob/2be466401adc63ae7c04c9b27e074d7aab194a7b/adafruit_max7219/matrices.py#L54

Here is the stack trace that you get when it's missing:
```
code.py output:
Cycle start
Could not find font file font5x8.bin
Traceback (most recent call last):
  File "code.py", line 44, in <module>
  File "adafruit_max7219/matrices.py", line 54, in text
  File "adafruit_framebuf.py", line 397, in text
  File "adafruit_framebuf.py", line 472, in __init__
OSError: [Errno 2] No such file/directory: 'font5x8.bin'

```

**Comment by caternuson** [comment]
Might be more of an issue with `adafruit_frambebuf`, since it has that font file hardwired in as default in several places.

It's here if you need it:
https://github.com/adafruit/Adafruit_CircuitPython_framebuf/blob/master/examples/font5x8.bin

**Comment by FlantasticDan** [comment]
@caternuson I think that you're right, the font should be bundled with `adafruit_framebuf` because it's a hardcoded default. However, in this library the `text` method provides no functionality to change the default font:
https://github.com/adafruit/Adafruit_CircuitPython_MAX7219/blob/9e5528117b3a7c20e530ada62c4cbf8d268e7df8/adafruit_max7219/matrices.py#L53

Perhaps it makes sense to add a keyword argument to pass an optional font down to `adafruit_framebuf`, something like:
```python
def text(self, strg: str, xpos: int, ypos: int, bit_value: int = 1, *, font_name: str = "font5x8.bin") -> None:
        """
        Draw text in the 8x8 matrix.

        :param str strg: string to place in to display
        :param int xpos: x position of LED in matrix
        :param int ypos: y position of LED in matrix
        :param int bit_value: > 1 sets the text, otherwise resets
        :param str font_name: path to binary font file (default: "font5x8.bin")
        """
        self.framebuf.text(strg, xpos, ypos, bit_value, font_name=font_name)
```

[This is the corresponding `adafruit_framebuf` function call.](https://github.com/adafruit/Adafruit_CircuitPython_framebuf/blob/958171e036fe5014d7cedc027e17029717053087/adafruit_framebuf.py#L383)

I'm especially interested in this font option because I'm working on a project that uses a smaller [3x5 matrix font](https://gist.github.com/FlantasticDan/587cb17a41d551f07ab93db18fba4fb2), I just haven't figured out the `.bin` font format yet.

**Comment by jposada202020** [comment]
maybe a Pr is in place?

Thanks @elpekening for the info.
